#!/usr/bin/env ansible-playbook
# WSO2 API Manager 3.2.0 install
---

- name: Install database
  hosts: database
  become: false
  serial: 1
  gather_facts: false
  tags:
    - database
  roles:
    - role: wso2db

- name: Install WSO2 API Manager
  hosts: apim
  become: true
  gather_facts: false
  tags:
    - apim
    - install
  roles:
    - role: wso2zip
    - role: apim
...
