#!/usr/bin/env ansible-playbook
# WSO2 API Manager 3.2.0 install
---

- name: Install galaxy roles
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: ansible-galaxy install
      command: ansible-galaxy install -p roles -r roles/requirements.yml
      args:
        creates: roles/java/molecule
      tags:
        - galaxy
        - roles
        - install

- name: Install database
  hosts: database
  become: true
  serial: 1
  gather_facts: true
  tags:
    - database
    - install
  roles:
    - role: postgres
      use_postgresql_org_repo: false
      base_postgres_m: 10

- name: Apply common configuration to wso2apim nodes
  hosts: apim
  gather_facts: true
  become: true
  roles:
    - role: common
      when: ansible_os_family != 'Windows'
      tags:
        - common
        - install
    - role: java
      tags:
        - java
        - install

- name: Install WSO2 API Manager
  hosts: apim
  gather_facts: false
  tags:
    - apim
    - install
  roles:
    - role: apim
