---
target: /mnt # Product installation directory
product_package_location: files
# List of configuration file templates, and the paths they should be written to
config_files:
  - { src: 'carbon-home/repository/conf/deployment.toml.j2',
      dest: '{{ carbon_home }}/repository/conf/deployment.toml' }
  - { src: 'carbon-home/repository/conf/carbon.xml.j2',
      dest: '{{ carbon_home }}/repository/conf/carbon.xml' }

# Gateway configurations
gateway_environments:
  - { type: 'hybrid',
      name: 'Default',
      description: 'This is a hybrid gateway that handles both production and sandbox token traffic.',
      service_url: "https://{{ ansible_fqdn }}:${mgt.transport.https.port}/services/",
      ws_endpoint: "ws://{{ ansible_fqdn }}:9099",
      wss_endpoint: "wss://{{ ansible_fqdn }}:8099",
      http_endpoint: "http://{{ ansible_fqdn }}:${http.nio.port}",
      https_endpoint: "https://{{ ansible_fqdn }}:${https.nio.port}",
      websub_event_receiver_http_endpoint: "http://{{ ansible_fqdn }}:9021",
      websub_event_receiver_https_endpoint: "https://{{ ansible_fqdn }}:8021"}

# Analytics
stream_processor_rest_api_url: https://localhost:7444
stream_processor_rest_api_username: ${admin.username}
stream_processor_rest_api_password: ${admin.password}
stream_processor_username: ${admin.username} # Stream processor connection credentials
stream_processor_password: ${admin.password} # Stream processor connection credentials

# Server URL of the Authentication service. Make sure to import the Key Manager's public certificate to WSO2 API-M's
# client-truststore.jks. For more information, see https://docs.wso2.com/display/ADMIN44x/Creating+New+Keystores
key_manager_server_url: "https://{{ ansible_fqdn }}:${mgt.transport.https.port}${carbon.context}services/"

# API Store related configurations
api_devportal_url: "https://{{ ansible_fqdn }}:${mgt.transport.https.port}/devportal"
api_devportal_server_url: "https://{{ ansible_fqdn }}:${mgt.transport.https.port}${carbon.context}services/"
