---
target: /mnt # Product installation directory
product_package_location: files
# List of configuration file templates, and the paths they should be written to
config_files:
  - { src: 'carbon-home/repository/conf/deployment.toml.j2',
      dest: '{{ carbon_home }}/repository/conf/deployment.toml' }
  - { src: 'carbon-home/repository/conf/carbon.xml.j2',
      dest: '{{ carbon_home }}/repository/conf/carbon.xml' }
