---
product_name: wso2am
product_version: 3.2.0
product_url: 'https://github.com/wso2/product-apim/releases/download/v'
remote_pack: "{{ product_url ~ product_version }}/{{ product_name ~ '-' ~ product_version }}.zip"
hostname: "{{ ansible_fqdn }}"
ports_offset: 0

...
